# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 15:06
from __future__ import unicode_literals

import json

from django.db import migrations
from django.utils.text import slugify


def forwards(apps, schema_editor):
    filepath = 'polls_app/polls.json'
    Poll = apps.get_model('polls_app', 'Poll')
    Question = apps.get_model('polls_app', 'Question')

    with open(filepath) as fp:
        contents = fp.read()
        data = json.loads(contents)
        for poll in data:
           poll_instance = Poll.objects.create(name=poll['pollName'],
                                               slug=slugify(poll['pollName']))
           for question in poll['questions']:
               question_instance = Question.objects.create(
                   question_text=question['questionName']
               )
               for option in question['options']:
                   question_instance.choice_set.create(choice_text=option)
               poll_instance.questions.add(question_instance)
        

def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            forwards, backwards
        )
    ]
